"""Notification tokens

Revision ID: 2c622aeb374f
Revises: 52d78810c413
Create Date: 2023-12-18 20:04:28.225413+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c622aeb374f'
down_revision = '52d78810c413'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_token',
    sa.Column('id', sa.String(length=250), nullable=False),
    sa.Column('company_id', sa.String(length=250), nullable=False),
    sa.Column('token', sa.String(length=250), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['face_recognition.company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='face_recognition'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_token', schema='face_recognition')
    # ### end Alembic commands ###
