"""first migration

Revision ID: 48419ec60acb
Revises: 
Create Date: 2023-11-16 20:09:28.700804+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48419ec60acb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.String(length=250), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='face_recognition'
    )
    op.create_table('face_detection',
    sa.Column('id', sa.String(length=250), nullable=False),
    sa.Column('company_id', sa.String(length=250), nullable=False),
    sa.Column('image_url', sa.String(length=250), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['face_recognition.company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='face_recognition'
    )
    op.create_table('watchlist',
    sa.Column('id', sa.String(length=250), nullable=False),
    sa.Column('face_detection_id', sa.String(length=250), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['face_detection_id'], ['face_recognition.face_detection.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='face_recognition'
    )
    op.drop_table('alembic_version')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name='alembic_version_pkc')
    )
    op.drop_table('watchlist', schema='face_recognition')
    op.drop_table('face_detection', schema='face_recognition')
    op.drop_table('company', schema='face_recognition')
    # ### end Alembic commands ###
