"""Shoplifting table is added

Revision ID: 361fcc68744b
Revises: bdbcdd7fdd39
Create Date: 2023-11-28 21:13:35.630775+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '361fcc68744b'
down_revision = 'bdbcdd7fdd39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('shoplifting',
    sa.Column('id', sa.String(length=250), nullable=False),
    sa.Column('company_id', sa.String(length=250), nullable=False),
    sa.Column('face_detection_id', sa.String(length=250), nullable=False),
    sa.Column('video_url', sa.String(length=250), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['face_recognition.company.id'], ),
    sa.ForeignKeyConstraint(['face_detection_id'], ['face_recognition.face_detection.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='face_recognition'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shoplifting', schema='face_recognition')
    # ### end Alembic commands ###
