"""Company rtsp url table

Revision ID: 52d78810c413
Revises: 361fcc68744b
Create Date: 2023-12-09 12:11:09.805985+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52d78810c413'
down_revision = '361fcc68744b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_rtsp_url',
    sa.Column('id', sa.String(length=250), nullable=False),
    sa.Column('company_id', sa.String(length=250), nullable=False),
    sa.Column('rtsp_url', sa.String(length=2500), nullable=False),
    sa.Column('path', sa.String(length=250), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='face_recognition'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_rtsp_url', schema='face_recognition')
    # ### end Alembic commands ###
